Add pre-validate step to check if the image name has already been used
hashicorp/packer-plugin-openstack pull request #106
Opened 2023-07-19 05:41 UTC by shengxpa

For the packer image build on the Openstack platform, there is a lack of a pre-validate step for the image name like in the [packer-plugin-amazon](https://github.com/hashicorp/packer-plugin-amazon/blob/main/builder/common/step_pre_validate.go) plugin, resulting in the name of the built image often being repeated like this:
![image](https://github.com/hashicorp/packer-plugin-openstack/assets/130132306/09794cd6-6910-4aef-b5d0-375c5afc2987)
It always causes some confusion when using image.

In this PR, a pre-validate step has been added to check if the image name has already been used. If the image name has already been used, an error will be output. "packer_force" parameter can be used to skip the pre-validate step when it be set to 'true' like the logic of [packer-plugin-amazon](https://github.com/hashicorp/packer-plugin-amazon/blob/877a7b15d179e840e1e3f191644c0eeb362551cb/builder/common/step_pre_validate.go#L82) plugin.

2023-07-19 05:42 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-openstack?pullRequest=106)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-openstack?pullRequest=106)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-openstack?pullRequest=106).</sub>

2023-07-25 02:02 UTC, shengxpa commented
Anyone can help have a review?

2023-08-07 07:40 UTC, shengxpa commented
@nywilken

2023-08-22 20:47 UTC, nywilken requested changes
Thanks for opening up this change. Our focus has been on a few plugin changes so I do apologize for the delayed review. 

 I took a quick look at the OpenStack glance image creation API to see why this wasn't implemented previously. I found that the API allows for this and OpenStack itself does not consider it an issue because the ids are unique. This leaves me to think that adding this change, while logical, may break expectation for users. 

In addition to the prevalidation step the use of -force generally implies to force a build when artifacts from a previous build prevent a build from running. This is not really the case here seeing as OpenStack does allow images to have the same name.

Have you considered using a timestamp when generating the image name? 

The use of the timestamp function with Packer templates is a common practice for avoiding duplicate image names. It is a little tricky seeing as OpenStack does allow it. If you think this feature would benefit users over setting a timestamp then I would suggest adding an optional attribute to change the default behavior of the glance API such as 

```
prevent_duplicate_image_name (boolean) - Set to true to check that no existing image has the same image name. If the image name is already in use the builder will exit with an error. Defaults to false
```

Please let me know what you think?

2023-10-10 19:40 UTC, nywilken commented
Closing since there have been no updates to the issue. If you believe this is still an issue please or should be a feature please open an issue first so that other users can vote on and provide insight into the usage. Thanks!

2023-10-10 19:40 UTC, closed without merging