[bug fix] Add retry logic to fix the server terminate failed issue
hashicorp/packer-plugin-openstack pull request #94
Opened 2023-02-22 06:50 UTC by zhenggu

In our openstack environment, we randomly get the error while terminating the server on the end of packer build.
It causes many useless VMs existing in our openstack.
The error is like this:
![error](https://user-images.githubusercontent.com/14901481/220543441-bf5c744a-c7bc-411a-bc69-7a9893f2c95b.png)
The following is the stack trace from OCP service side when the issue happened.
```
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions [req-965cda1d-a06d-42f6-ade4-4067bcf951ad f2540ed3657741ad9485a440c24aa45a f361dec2c1bd43789b6f5a96f3f252ba - default default] Unexpected exception in API method
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions Traceback (most recent call last):
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/extensions.py", line 338, in wrapped
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions     return f(*args, **kwargs)
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/api/openstack/compute/deferred_delete.py", line 64, in _force_delete
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions     self.compute_api.force_delete(context, instance)
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/compute/api.py", line 166, in inner
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions     return function(self, context, instance, *args, **kwargs)
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions   File "/usr/lib/python2.7/site-packages/nova/compute/api.py", line 139, in inner
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions     method=f.__name__)
2023-02-08 03:07:36.912 5493 ERROR nova.api.openstack.extensions InstanceInvalidState: Instance 983e2da3-fcaa-45cb-ba2d-1aa21bf9ec37 in task_state image_uploading. Cannot force_delete while the instance is in this state. 
```
According to the logic of [packer-plugin-openstack](https://github.com/hashicorp/packer-plugin-openstack/blob/ddf068815e36b0925ef06e8c3aea2a5caa8d15a9/builder/openstack/step_create_image.go#L145), when the status of the image has become `active`, then packer will try to remove the temporary VM immediately, if the remove action fails, then the error will happen.

From the stack trace, when the status of the image has been changed to `active`, the image uploading task of the VM hasn't been finished.

Then the VM delete action will be failed, and OCP service will report: `Internal Server Error`, and the HTTP error code is 500.

In this PR, a retry logic has been added to detect whether it meets `Internal Server Error`, if so, it will have a retry up to 20 seconds.

2023-02-22 06:50 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-openstack?pullRequest=94)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-openstack?pullRequest=94)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-openstack?pullRequest=94).</sub>

2023-03-31 02:45 UTC, zhenggu commented
Anyone can help to have a review?

2023-04-07 20:09 UTC, nywilken requested changes
@zhenggu apologies for the delayed review here. I had time to look over the changes and left a small suggestion to the code changes. Otherwise I think this looks good to go. Please let me know your thoughts and if there are any issues with the suggested code. 

If all works as expected I will merge the changes once updated and cut an immediate release.

2023-04-07 20:09 UTC, nywilken commented on builder/openstack/step_run_source_server.go
> +			break
Hey @zhenggu I had a little trouble immediately understanding what is going on. I suggest a slight refactor to help with readability. Could you validate that the suggested change works as intended please. 
```go
	for {
		if config.ForceDelete {
			err = servers.ForceDelete(computeClient, s.server.ID).ExtractErr()
		} else {
			err = servers.Delete(computeClient, s.server.ID).ExtractErr()
		}

		if err == nil {
			break
		}

		if _, ok := err.(gophercloud.ErrDefault500); !ok {
			ui.Error(fmt.Sprintf("Error terminating server, may still be around: %s", err))
			return
		}

		if numErrors < maxNumErrors {
			numErrors++
			log.Printf("Error terminating server on (%d) time(s): %s, retrying ...", numErrors, err)
			time.Sleep(2 * time.Second)
			continue
		}
		ui.Error(fmt.Sprintf("Error terminating server, maximum number (%d) reached: %s", numErrors, err))
		return
	}
```

2023-04-13 06:50 UTC, zhenggu commented
Hi @nywilken, I have refactored the code as your suggestion, and it works fine, the following is the packer log on this case, please help to approve it.
```
==> openstack: Terminating the source server: d74fcb01-fd63-4f4c-b0ff-3fe50eef8a1e ...
2023/04/13 14:44:10 packer-builder-openstack plugin: Error terminating server on (1) time(s): Internal Server Error, retrying ...
2023/04/13 14:44:23 packer-builder-openstack plugin: Waiting for state to become: [DELETED]
2023/04/13 14:44:25 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:30 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:34 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:38 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:42 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:46 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:50 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:55 packer-builder-openstack plugin: Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2023/04/13 14:44:59 packer-builder-openstack plugin: [INFO] 404 on ServerStateRefresh, returning DELETED
==> openstack: Deleting temporary keypair: packer_643799ab-4e31-f28e-a141-35125c5e0453 ...
Build 'openstack' finished after 48 minutes 26 seconds.
```

2023-04-13 10:55 UTC, nywilken approved these changes
Thank you @zhenggu. I'll merge and release once all goes green. Cheers!

2023-04-13 11:03 UTC, merged

2023-04-13 11:04 UTC, nywilken commented
I fixed the goimports lint check and merged directly. Thank you again.